app:
  h2dbPath: G:\data\development\capital4j-client\h2
  main-fxml: /fxml/MainView.fxml
  main-style: /css/mainStyle.css

spring:
  datasource:
    url: jdbc:h2:file:${app.h2dbPath};DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: capital4j-client
    password: capital4j-client
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: Capital4J-Client



