app:
  data-path: G:\data\development\capital4j-client
  h2db-path: ${app.data-path}\h2
  python-path: ${app.data-path}\python
  python-win-amd64-url: https://www.python.org/ftp/python/3.12.3/python-3.12.3-embed-amd64.zip
  tmp-path: ${app.data-path}\tmp

spring:
  shardingsphere:
    mode:
      type: Standalone
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:file://${app.h2db-path};DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: capital4j-client
        password: capital4j-client
    rules:
      sharding:
        tables:
          k_line_his_cn:
            actual-data-nodes: ds.k_line_his_cn_$->{1999..2030}
            table-strategy:
              standard:
                sharding-column: date
                sharding-algorithm-name: k_line_his_cn_by_year
        sharding-algorithms:
          k_line_his_cn_by_year:
            type: INLINE
            props:
              algorithm-expression: k_line_his_cn_$->{date.year}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: Capital4J-Client
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=600s
  thymeleaf:
    check-template-location: false

server:
  port: 18080