app:
  data-path: G:\data\development\capital4j-client
  h2db-path: ${app.data-path}\h2
  python-path: ${app.data-path}\python
  python-win-amd64-url: https://www.python.org/ftp/python/3.12.3/python-3.12.3-embed-amd64.zip
  tmp-path: ${app.data-path}\tmp
  rocksdb:
    path: ${app.data-path}\rocksdb

server:
  port: 18080

spring:
  datasource:
      url: jdbc:h2:file:${app.h2db-path};DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      driverClassName: org.h2.Driver
      username: neo4j
      password: capital4j-client
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Capital4J-Client
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=600s
  data:
    redis:
      host: localhost
      port: 16379
  neo4j:
    uri: bolt://localhost:17687
    authentication:
      username: capital4j-client
      password: capital4j-client


logging:
  level:
    sql: info
